version: 2

sources:
  - name: clickhouse_silver
    description: "Silver tables in ClickHouse (already transformed by Python)"
    schema: ""
    loader: python_script
    
    tables:
      - name: silver_customers
        description: "Unified customer data from PG and Kaggle"
        
      - name: silver_claims
        description: "Unified claims data from PG and Kaggle"
